export default {
  'en-us': {
    barText: 'Blog',
    postsTitle: 'All posts',
    list: [
      {
        title: 'iUML-B New Release',
        author: 'Colin Snook',
        dateStr: '2017-07-05',
        desc: 'iUML-B New Release',
        link: '/en-us/blog/iUMLB.html',
      },
      {
        title: 'XEvent-B 0.0.6 Release',
        author: 'Son Thai Hoang',
        dateStr: '2017-07-22',
        desc: 'XEvent-B 0.0.6 Release',
        link: '/en-us/blog/XEventB.html',
      },
      {
        title: 'XEvent-B 0.0.7 Release',
        author: 'Son Thai Hoang',
        dateStr: '2017-08-22 ',
        desc: 'XEvent-B 0.0.7 Release',
        link: '/en-us/blog/XEventB1.html',
      },
      {
        title: 'CamilleX 1.0.0 Release',
        author: 'Son Thai Hoang',
        dateStr: '2018-11-12',
        desc: 'CamilleX 1.0.0 Release',
        link: '/en-us/blog/CamilleX.html',
      },
      // {
      //   title: 'The fifth blog',
      //   author: 'author5',
      //   dateStr: 'April 22nd，2018',
      //   desc: 'Blog description, some text to sum up the main content of the blog',
      //   link: '/en-us/blog/blog5.html',
      // },
      // {
      //   title: 'The sixth blog',
      //   author: 'author6',
      //   dateStr: 'April 22nd，2018',
      //   desc: 'Blog description, some text to sum up the main content of the blog',
      //   link: '/en-us/blog/blog6.html',
      // },
      // {
      //   title: 'The seventh blog',
      //   author: 'author7',
      //   dateStr: 'April 22nd，2018',
      //   desc: 'Blog description, some text to sum up the main content of the blog',
      //   link: '/en-us/blog/blog7.html',
      // },
    ],
  },
  'zh-cn': {
    barText: '博客',
    postsTitle: '所有文章',
    list: [
      {
        title: 'iUML-B New 发布',
        author: 'Colin Snook',
        dateStr: '2017-07-05',
        desc: 'iUML-B New 发布',
        link: '/zh-cn/blog/iUMLB.html',
      },
      {
        title: 'XEvent-B 0.0.6 发布',
        author: 'Son Thai Hoang',
        dateStr: '2017-07-22',
        desc: 'XEvent-B 0.0.6 发布',
        link: '/zh-cn/blog/XEventB.html',
      },
      {
        title: 'XEvent-B 0.0.7 发布',
        author: 'Son Thai Hoang',
        dateStr: '2017-08-22 ',
        desc: 'XEvent-B 0.0.7 发布',
        link: '/zh-cn/blog/XEventB1.html',
      },
      {
        title: 'CamilleX 1.0.0 发布',
        author: 'Son Thai Hoang',
        dateStr: '2018-11-12',
        desc: 'CamilleX 1.0.0 发布',
        link: '/zh-cn/blog/CamilleX.html',
      },
    ],
  },
};
